version = 0.1
[default.deploy.parameters]
stack_name = "saldo-sensei-auth"
resolve_s3 = true
s3_prefix = "saldo-sensei-auth"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
