version = 0.1
[default.deploy.parameters]
stack_name = "saldo-sensei"
resolve_s3 = true
s3_prefix = "saldo-sensei"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
parameter_overrides = "CognitoUserPoolArn=\"\""
