AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: 'AWS SAM template for creating DynamoDB tables for the SaldoSensei application.'

Resources:
  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Transactions
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: dev

Outputs:
  TransactionsTableName:
    Description: Name of the Transactions table
    Value: !Ref TransactionsTable
  TransactionsTableArn:
    Description: ARN of the Transactions table
    Value: !GetAtt TransactionsTable.Arn
